### ISSUE TITLE
How on earth do I install this?!

### ISSUE THREAD

**Issue by BwahFox** [MCPI-Revival/Mycelium#3]
I'm new to GitHub, and I want to make a Minecraft pi edition server.  Only problem is, I don't know how to install this to do so.

If I can have instructions, that would be useful

**Comment by NoozAbooz** [comment]
https://mcpirevival.tk/howto/creating-servers.html

**Comment by torralbaa** [comment]
Hello! If you want to make a MCPI server, I would recommend the link @mobilegmYT sent, since this is a framework, and isn't complete yet, according to the author.

**Comment by BwahFox** [comment]
oh ok
